apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter 
  namespace: flux-system         
spec:
  targetNamespace: kube-system   
  interval: 10m0s
  chart:
    spec:
      chart: karpenter   
      version: ">=1.0.0"
      
      sourceRef:
        kind: HelmRepository
        name: karpenter 
        namespace: flux-system 
      interval: 5m0s