apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: payment-app
  namespace: app         
spec:
  targetNamespace: app   
  interval: 10m0s
  chart:
    spec:
      chart: payment-app-chart  
      version: ">=1.0.0"
      
      sourceRef:
        kind: HelmRepository
        name: payment-app-repo
        namespace: flux-system 
      interval: 5m0s

  values:
    # Point to the real Azure Database
    db:
      host: "paymentapp-payment-db.postgres.database.azure.com" 
      name: "paymentapp-payment-db"